contrastive:
  num_iterations: 400
  lr: 0.0005
  weight_decay: 0.0001
  batch_size: 32
  encoder_name: "resnet50"
  pretrained_encoder: False
regression:
  num_iterations: 100
  lr: 0.005
  weight_decay: 0
  batch_size: 32
  encoder_name: "resnet50"
  pretrained_encoder: False